Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ScanAndGo.Models;

namespace ScanAndGo.Controllers
{
    public class CartsController : Controller
    {
        // GET: Carts
        ScanAndGoContext context = new ScanAndGoContext();

        public ActionResult Indexes()
        {
            if (Session["UserID"] != null)
            {
                List<Product> see = context.Products.ToList();
                return View(see);
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
            
        }

        public ActionResult AddToCart()
        {
            ViewBag.MenuItemID = new SelectList(context.Products.ToList(), "Id", "Id");
            return View();
        }
        [HttpPost]
        public ActionResult AddToCart(Cart c)
        {
            ViewBag.MenuItemID = new SelectList(context.Products.ToList(), "Id", "Name");
            Product menu = context.Products.Where(m => m.Id ==c.Id ).FirstOrDefault();
            Cart cart = new Cart();
            cart.productId = c.Id;
            cart.userId = Convert.ToInt32(Session["UserID"]);
            cart.quantity = c.quantity;
            context.Carts.Add(cart);
            context.SaveChanges();

            return RedirectToAction("ViewCart");
        }

        public ActionResult ViewCart()
        {
            if (Session["UserID"] != null)
            {
                int cartContentsCount = context.Carts.Select(c => c.Id).Count();
                int user = Convert.ToInt32(Session["UserID"]);
                if (cartContentsCount < 1)
                    return RedirectToAction("EmptyCart");
                return View(context.Carts.Where(u => u.userId == user).ToList());
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
           
        }

        public ActionResult EmptyCart()
        {
            return View();
        }

        public ActionResult Delete(int? cartId)
        {
            Cart record = context.Carts.Where(k => k.Id == cartId).SingleOrDefault();
            context.Carts.Remove(record);
            context.SaveChanges();
            return RedirectToAction("ViewCart");
        }
        public double ComputeTotalValue()
        {
            return context.Carts.Sum(e => e.Product.Price);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ScanAndGo.Models;

namespace ScanAndGo.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        ScanAndGoContext context = new ScanAndGoContext();
        public ActionResult GenerateOrder()
        {

            if (Session["UserID"] != null)
            {
                int cartContentsCount = context.Carts.Select(c => c.Id).Count();
                int user = Convert.ToInt32(Session["UserID"]);
                if (cartContentsCount < 1)
                    return RedirectToAction("EmptyCart");
                return View(context.Carts.Where(u => u.userId == user).ToList());
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public ActionResult PaymentFailed()
        {
            int user = Convert.ToInt32(Session["UserID"]);
            ViewBag.total = context.Carts.Where(u => u.userId == user).Sum(e => e.Product.Price * e.quantity);
            return View();
        }

        public ActionResult pay()
        {

            if (Session["UserID"] != null && context.Carts.Select(c => c.Id).Count() >=1)
            {
                int user = Convert.ToInt32(Session["UserID"]);
                double total = context.Carts.Where(u => u.userId == user).Sum(e => e.Product.Price * e.quantity);
                double balance = Convert.ToInt32(Session["Balance"]) - total;
                
                if (total < Convert.ToInt32(Session["Balance"]))
                {
                    ViewBag.paid = total;
                    context.Carts.RemoveRange(context.Carts.Where(u => u.userId == user));
                    var selectedUser = context.Users.Single(i => i.Id == user);
                    selectedUser.Balance = Convert.ToInt32(balance);
                    context.SaveChanges();
                    
                    Session["Balance"] = balance;
                    return View();
                }
                else return RedirectToAction("PaymentFailed", "Order");
            }
            else
            {
                return View();
            }
        }
    }
}

Views/Order/GenerateOrder.cshtml
@model IEnumerable<ScanAndGo.Models.Cart>
@{
    ViewBag.Title = "GenerateOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h4 style="color:maroon"> Welcome @Session["UserName"].ToString()</h4>
<div style="position:absolute; right:200px">@Html.ActionLink("Logout", "LogOut", "Account")</div>
<h2>Your Order</h2>

<table class="table" style="width:500px; align-items:center; background-color:aliceblue">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Price) / Item
        </th>
        <th>
            Total @Html.DisplayNameFor(model => model.Product.Price)
        </th>


    </tr>
    @{ double Total = 0; double TotalPrice = 0;}

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Price)
                @{ Total += (item.Product.Price * item.quantity);}
            </td>
            <td>
                @{ TotalPrice = (item.Product.Price * item.quantity);}@TotalPrice
            </td>

        </tr>
    }
    <tr>

        <th>
            Total
        </th>
        <td>
        </td>
        <td>
        </td>
        <th>
            @Total
        </th>

    </tr>
</table>
<p style="text-align :center"><strong>Your Shopable Wallet Balance = @Session["Balance"]</strong></p>
<p style="text-align :center"><strong>@Html.ActionLink("Pay Via Wallet", "pay", "Order")</strong></p>

<div>
    Want To Modify Your Order.
    @Html.ActionLink("Click here", "ViewCart", "Carts")

</div>

Views/Order/PaymentFailed.cshtml

@{
    ViewBag.Title = "PaymentFiled";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Payment Failed</h2>
@{double diff = 0; }

<br />
<br />
Dear @Session["Username"]
<br />
Your Order value Exceeds your Wallet Balance
<br />
<br />


<table class="table" style="width:300px; align-items:center">
    <tr>

        <td>
            Your Order Total is
        </td>
        <th>
            @ViewBag.total
        </th>
    </tr>

    <tr>

        <td>
            Your Wallet Balance is

        </td>
        <th>
            @Session["Balance"]
        </th>

    </tr>
</table>

Recharge Your Wallet With Ammount @{diff = @ViewBag.total - Convert.ToDouble(@Session["Balance"]);}@diff To Continue Your Shopping Or  @Html.ActionLink("Remove", "ViewCart", "Carts") Some Item from Order To Continue

Views/Order/pay.cshtml

@{
    ViewBag.Title = "pay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Payment Successfull</h2>
<br />
<br />Total Ammount of @ViewBag.paid is Paid for Your Order from Your Wallet.<br />
Your Remaining Wallet Balance is 
@Session["Balance"]
<br />
<br />
Thank You @Session["Username"] for Shopping With Us.
<br />Have A Good Day and
Please Visit Again..


